name: PHP CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    environment:
      name: Production
      url: http://${{ secrets.SSH_HOST_APACHE }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # ... (يمكنك وضع خطوات CI الأخرى هنا لاحقاً إذا كنت تريد) ...
    # (على سبيل المثال:
    # - name: Setup PHP
    #   uses: shivammathur/setup-php@v2
    #   with:
    #     php-version: '8.2'
    #     extensions: mbstring, xml, curl
    #     tools: composer, phpunit
    #
    # - name: Install Composer dependencies
    #   run: composer install --no-dev --optimize-autoloader
    #
    # - name: Run PHPStan
    #   run: vendor/bin/phpstan analyse
    # )


    - name: Deploy to Apache2 Server
      if: success() && github.ref == 'refs/heads/main'
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST_APACHE }}
        username: ${{ secrets.SSH_USERNAME_APACHE }}
        key: ${{ secrets.SSH_PRIVATE_KEY_APACHE }}
        port: 22
        script: |
          cd ${{ secrets.DEPLOY_PATH_APACHE }}
          git pull origin main
          composer install --no-dev --optimize-autoloader
          sudo chown -R www-data:www-data ${{ secrets.DEPLOY_PATH_APACHE }}
          sudo chmod -R 755 ${{ secrets.DEPLOY_PATH_APACHE }}
          sudo systemctl reload apache2
          sudo systemctl reload php8.2-fpm
          echo "Deployment successful to Apache2!"
