- name: Deploy to Apache2 Server # هذه هي خطوة النشر الجديدة
  if: success() && github.ref == 'refs/heads/main' # انشر فقط إذا نجحت CI وعلى فرع main
  uses: appleboy/ssh-action@v1.0.3
  with:
    host: ${{ secrets.SSH_HOST_APACHE }}
    username: ${{ secrets.SSH_USERNAME_APACHE }}
    key: ${{ secrets.SSH_PRIVATE_KEY_APACHE }}
    port: 22 # منفذ SSH الافتراضي
    script: |
      cd ${{ secrets.DEPLOY_PATH_APACHE }}
      git pull origin main # لسحب أحدث كود إلى الخادم
      composer install --no-dev --optimize-autoloader # تثبيت التبعيات للإنتاج
      sudo chown -R www-data:www-data ${{ secrets.DEPLOY_PATH_APACHE }} # ضبط الأذونات
      sudo chmod -R 755 ${{ secrets.DEPLOY_PATH_APACHE }} # ضبط الأذونات
      sudo systemctl reload apache2 # إعادة تحميل Apache2 بعد نشر التغييرات
      sudo systemctl reload php8.2-fpm # إعادة تحميل PHP-FPM إذا لزم الأمر
      echo "Deployment successful to Apache2!"
